#apiVersion: v1
#kind: PersistentVolume
#metadata:
#    name: mysql
#    labels:
#        type: local
#spec:
#    storageClassName: mysql
#    accessModes:
#        - ReadWriteOnce
#    capacity:
#        storage: 1Gi
#    hostPath:
#        path: /var/lib/mysql/
#
#---
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
