apiVersion: v1
kind: Service
metadata:
        name: phpmyadmin-service
        labels:
                app: phpmyadmin-yopark
spec:
        selector:
                app: phpmyadmin-yopark
        type: LoadBalancer
        ports:
                - port: 5000
                  name: phpmyadmin-port
                  targetPort: 5000
                  nodePort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
        name: phpmyadmin-deployment
        labels:
                app: phpmyadmin-yopark
spec:
        selector:
                matchLabels:
                        app: phpmyadmin-yopark
        replicas: 1
        template:
                metadata:
                        name: phpmyadmin-pod
                        labels:
                                app: phpmyadmin-yopark
                spec:
                        containers:
                                - name: phpmyadmin-container
                                  image: ft_phpmyadmin
                                  imagePullPolicy: Never
                                  ports:
                                          - containerPort: 5000
                                            name: phpmyadmin-port
