apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
        - 172.17.0.2-172.17.0.12
#- 192.168.99.200-192.168.99.210
