apiVersion: v1
kind: Secret
metadata:
  name: influxdb
  labels:
    app: influxdb
type: Opaque
# 아래의 값들은 DB를 INITIALIZATION 하는데 사용되는 값들이다.
# https://hub.docker.com/_/influxdb 주소 아래 쪽 확인하자.
stringData:
  INFLUXDB_CONFIG_PATH: /etc/influxdb/influxdb.conf
  INFLUXDB_ADMIN_USER: admin
  INFLUXDB_ADMIN_PASSWORD: tkdgur123
  INFLUXDB_DB: telegraf
  INFLUXDB_USER: user
  INFLUXDB_USER_PASSWORD: tkdgur123
