apiVersion: apps/v1
kind: Deployment
metadata: # metadata describes the deployment itself.
  name: ftps # deployment's name. Pods is named based on this.
  labels: # Deployment's label
    app: ftps
spec: # Set Deployment
  selector:
    matchLabels: # Control pods which have this label
      app: ftps
  template: # POD!!!
    metadata:
      labels:
        app: ftps # Pod's app label is ftps
    spec: # CONTAINER!!!
      containers: # container set
      - name: ftps # container's name
        image: ft_ftps # Select docker image
        imagePullPolicy: Never # Using local image.
        ports:
          - containerPort: 20
            hostPort: 20
          - containerPort: 21
            hostPort: 21
          - containerPort: 21100
            hostPort: 21100
          - containerPort: 21101
            hostPort: 21101
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          tcpSocket:
            port: 21
