apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  ports:
    - port: 5050
      name: wordpress
      targetPort: 5050
  externalIPs:
      - 192.168.99.184
