apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
    nodePort: 80
  - port: 443
    name: https
    protocol: TCP
    targetPort: 443
    nodePort: 443
  - port: 22
    name: ssh
    protocol: TCP
    targetPort: 22
    nodePort: 22
